default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DATABASE_USERNAME"] || "root" %>
  password: <%= ENV["DATABASE_PASSWORD"] || "" %>
  host: <%= ENV["DATABASE_HOST"] || "127.0.0.1" %>
  port: <%= ENV["DATABASE_PORT"] || 3306 %>

development:
  <<: *default
  database: desafio_voll

test:
  <<: *default
  database: test_database
  username: root
  password: 
  host: 127.0.0.1
  socket: 
